### ISSUE TITLE
O original saiu do ar por ameaça de processo

### ISSUE THREAD

**Issue by gabrielbarros** [caioalonso/dolarlilas#1]
Oi, @caioalonso 

Fui que criei a página original, mas recebi um e-mail de "Cease and Desist", com uma sutil ameaça de processo, alegando que eu estava usando a marca deles.

Então acho melhor renomear para "Dólar Nu" ou "Dolar Roxinho", mudar a URL, apagar o README.md e mudar a cor RGB, já que eles se incomodaram com isso e podem querer ir atrás de você também.

Abraços.

**Comment by caioalonso** [comment]
Obrigado pelo alerta, @gabrielbarros. Estava curioso mesmo sobre por que o projeto havia desaparecido. Por trás da roupagem moderninha e descolada vemos que ainda tem a mesma mentalidade antiga de processar e calar até mesmo quem só quer saber quanto vai ter que pagar.

Removi todas as menções a nomes de empresas, alterei a cor para um tom de lilás e renomeei o projeto para dolarlilas. Temo que "Dólar Nu" ou "Dólar Roxinho" possa ser próximo demais, visto que existem empresas de cartão de crédito que usam as palavras nu e roxinho como apelidos de seus produtos. Mas nenhuma usa lilás.

**Comment by caioalonso** [comment]
Tive uma ideia melhor, @gabrielbarros, será dolarnobanco. :smile:

**Comment by gabrielbarros** [comment]
Ficou muito bom. É melhor assim para evitar problemas com eles.
