### ISSUE TITLE
Site quebrado

### ISSUE THREAD

**Issue by rafacteixeira** [caioalonso/dolarlilas#2]
Oi pessoal.
Apenas para informar que o site atual está quebrando.

erro no console: 

`script.js:324 GET https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20json%20where%20url%3D%22https%3A%2F%2Fwww.bcb.gov.br%2Fapi%2Fconteudo%2Fpt-br%2FPAINEL_INDICADORES%2Fcambio%3F2019011017%22&format=json&callback=onReceiveData net::ERR_NAME_NOT_RESOLVED`

[]s

**Comment by caioalonso** [comment]
Obrigado por avisar, @rafacteixeira ! O Yahoo desligou a API. Reescreverei o trecho sem usá-la.

**Comment by yvesmariano** [comment]
https://twitter.com/ydn/status/1079785891558653952
